### ISSUE TITLE
bug in block-apps-local-admins.xml

### ISSUE THREAD

**Issue by jake-the-creative** [govau/desktop.gov.au#151]
When attempting to use the file as is, azure/intune barfs saying it is badly formatted.
On closer inspection it is. It has multiple roots of "<RuleCollection "
wrapping the whole file with 
`<AppLockerPolicy Version="1">`
`</AppLockerPolicy>`
gets it to pass validation and allows it to save

I haven't confirmed that that is the right/best solution to that problem though.

**Comment by zedzedzed** [comment]
@oobedan maybe one for you?

**Comment by oobedan** [comment]
Addressed in PR #155. Thanks, have exported from working config in our baseline tenant.

@jake-the-creative as for best way etc to do this, happy for any feedback on a better way to do it. We've been successful using this method for various agencies within a cloud setting, WDAC doesn't have the ability to do user/group-based restrictions hence applocker on top of any WDAC you're doing. The control around email, we recommend not applying the Exchange plan license and limiting Internet access at the proxy too. Blueprint does not provide an internet filtering capability it is implied that the agency has this in place.

**Comment by jake-the-creative** [comment]
The changed file still doesn't pass validation I don't think, it still has multiple roots.
I have just been throwing it through this as the first XML validator I found.
https://www.xmlvalidation.com/index.php?id=1&L=0
Have you tried importing that file into the gui as described in abac? 

https://www.desktop.gov.au/blueprint/abac/intune-configuration.html#acsc---applocker-lockdown-csp
Microsoft Endpoint Manager > Devices > Configuration profiles > Create Profile > Windows 10 and Later
That is what was failing for me. If it imports from CLI but fails from there then it's perhaps a documentation bug? or upstream if microsoft are emitting invalid xml?

Sorry I should have been clearer about "the best way to do this" I mean the best way to fix the specific bug on import not the overall system.

**Comment by oobedan** [comment]
Save the file as XML, import  using data type (String XML file) in OMA-URI? Does that work, just confirmed in my Intune tenant.

File here from my fork ->
(desktop.gov.au/block-apps-local-admins.txt at AppLocker-XML-config * oobedan/desktop.gov.au (github.com)<https://github.com/oobedan/desktop.gov.au/blob/AppLocker-XML-config/assets/files/abac/block-apps-local-admins.txt>)

***@***.***

**Comment by jake-the-creative** [comment]
Ahh my bad. I hadn’t actually tested it beyond the xml validation.
All works now. Thanks!

**Comment by oobedan** [comment]
No worries. It’s an export straight our of XML that is generated from AppLocker local GPMC so I don’t think it actually validates as a proper XML file. It just works if you import into Intune 😊

**Comment by zedzedzed** [comment]
PR has been merged abd closing this ticket off.
